# Generated by Django 3.1.2 on 2020-12-14 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='mensaje',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='receptor',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='titulo',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='estado',
        ),
    ]
